# Minimal Nav2 parameters for Tractobots
amcl:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    yaml_filename: ''
    frame_id: map

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_time.xml"

controller_server:
  ros__parameters:
    use_sim_time: false

planner_server:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false
