navsat_transform:
  ros__parameters:

    # ─── Core settings ─────────────────────────────────────────────
    frequency: 10.0
    delay: 0.0

    # ─── IMU heading adjustments ──────────────────────────────────
    magnetic_declination_radians: 0.0712094335   # ← update for your location
    yaw_offset: 1.5707963268                     # 90 deg = ENU → ROS

    # ─── Altitude & frame handling ────────────────────────────────
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
