name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ---------- ROS Humble ---------------------
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble

      # ---------- Extra test framework ----------
      - name: Install ament test harness (no linters)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-ament-cmake

      # ---------- Build --------------------------
      - name: colcon build
        run: |
          colcon build \
            --event-handlers console_direct+ \
            --cmake-args -DENABLE_LINT_TESTS=OFF

      # ---------- Test ---------------------------
      - name: colcon test
        run: |
          colcon test \
            --event-handlers console_direct+
      - name: colcon test-result
        run: |
          colcon test-result --verbose
