name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install ROS 2 (Humble)
      - name: Setup ROS 2
        run: |
          sudo apt update && sudo apt install -y curl gnupg2 lsb-release software-properties-common
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep2 python3-pip

      # 3. Install OS-level build tools
      - name: Install OS dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pytest

      # 4. Install ROS 2 package dependencies
      - name: rosdep install
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 5. Build the workspace
      - name: Colcon build
        run: |
          colcon build --symlink-install

      # 6. Run tests and report results
      - name: Colcon test
        run: |
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
